// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
export const SUPABASE_URL = 'https://nrgjaofrozgccdiebqwv.supabase.co';
export const SUPABASE_SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yZ2phb2Zyb3pnY2NkaWVicXd2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTM3MzE3NCwiZXhwIjoyMDYwOTQ5MTc0fQ.rpM6Fruwxq30AY35TXdePK-I_CXIg5lv1_7jpup7Rdk'
export const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yZ2phb2Zyb3pnY2NkaWVicXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzMxNzQsImV4cCI6MjA2MDk0OTE3NH0.GPWWb-yQhCcW0MRvH2veCaomF7uRUYJrddnTkeg5KP0';


export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
